config/routes.rb
Rails.application.routes.draw do


  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  
  root to: 'welcome#home'

  resources :users, except: [:index, :new, :create]


  get 'signup' => 'users#new'
  post 'signup' =>'users#create'
 
  get 'signin' => 'sessions#new' 
  post 'signin' => 'sessions#create'
  post 'signout' =>'sessions#destroy'

  
  resources :games, except: [:destroy] do
    resources :reviews, except: [:show]
  end
  
  get '/search' => 'games#search'
  resources :categories,only: [:index, :show]
  
 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :games
    validates :name, presence: true, uniqueness: {case_sensitive: false}
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :reviews
    has_many :users, :through => :reviews
    belongs_to :category 

    validates :title, presence: true, uniqueness: {case_sensitive: false}
    validates :image, presence:  { message: "Please enter a image URL" }
    validates :description, presence:  { message: "Please enter a description" }

    scope :ordered_by_title, -> { order(title: :asc) }
    scope :search_game, ->(search) {where("title LIKE ?", "%" + "#{search}" + "%")}

    def category_attributes=(hash_attr)
        if !hash_attr[:name].blank?
            self.category = Category.find_or_create_by(hash_attr)
        end

    end

end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :game

    validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password 
    has_many :reviews, dependent: :destroy
    has_many :games, :through => :reviews

    validates :username, presence: true
    validates :email, presence: true, uniqueness: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper

rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
   
private 

    def require_login
        redirect_to root_path unless logged_in?
    end

    def record_not_found(error)
        @message = error.message
        render :"layouts/error_page"
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_login
    
    def index
        @categories = Category.all
    end
    

    def show
        @category = Category.find_by_id(params[:id])

    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :require_login
    before_action :set_game_variable, except: [:index, :create, :new, :search]

    def index
        @games = Game.all.ordered_by_title
    end

    def show
        if !@game
            redirect_to games_path
        end
    end

    def new
        @game = Game.new
        @game.build_category
    end

    def create
        @game = Game.new(game_params)
            if  @game.valid?
                @game.save
                redirect_to game_path(@game)
            else 
                render :new
            end
    end

    def edit
        if @game
            @game.build_category
        else
            redirect_to games_path
        end
    end

    def update
        if @game.valid?
		    @game.update(game_params)
            redirect_to game_path(@game)
        else
            render :edit
        end
    end

    def search
            @games_search = Game.search_game(params[:search])
    end



    private

    def game_params
        params.require(:game).permit(:title, :image, :description, :category_id, :category_attributes => [:name])
    end

    def set_game_variable
        @game = Game.find(params[:id])
    end

    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :require_login
    before_action :set_game_reviews_variable, except:[:create]
    before_action :set_review_variable, except: [:index, :new, :create]
   
    
    def index
        @reviews = @game.reviews
    end

    def new
        @review = Review.new
    end 

    def create
        @review = Review.new(review_params)
        @review.user = current_user
            if  @review.valid?
                @review.save
                redirect_to game_reviews_path(@review.game)
            else 
                render :new
            end
    end

    def edit
        must_be_current_user
    end

    def update
        if @review.valid?
            @review.update(review_params)
            redirect_to game_reviews_path(@game)
        else
            render :edit 
        end
    end

    def destroy
        must_be_current_user
        @review.destroy
        redirect_to game_reviews_path(@game)
      end

    private

    def review_params
        params.require(:review).permit(:content, :game_id)
    end

    def must_be_current_user
       if  @review.user != current_user
        redirect_to game_reviews_path(@game)
       end
    end

    def set_game_reviews_variable
        @game = Game.find(params[:game_id])
    end

    def set_review_variable
        @review = Review.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
    def new
      if logged_in?
        redirect_to user_path(session[:user_id])
      end
    end 

    def create
        if !params[:password].blank? || !params[:user].blank?

          @user = User.find_by(email: params[:email])

            if !@user.blank?
              return head(:forbidden) unless @user.authenticate(params[:password])
              session[:user_id] = @user.id
              redirect_to user_path(@user)
            else
              flash[:message] = "Wrong Email or Password"  
              render :new
            end 

        else
          flash[:message] = "Can't leave the fields blank"  
          render :new
        end
    end

    def omniauth
     
      user = User.find_or_create_by(uid: auth[:uid], provider: auth[:provider]) do |u|
        u.email = auth[:info][:email]
        u.username = auth[:info][:name]
        u.password = SecureRandom.hex(12)
      
       end

       if user.valid?
          session[:user_id] = user.id
          redirect_to user_path(user)
       else
          redirect_to root_path
       end

    end

      
    def destroy
      session.clear
        redirect_to root_path 
    end

    private 

    def auth
      request.env['omniauth.auth']
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user_variable, except:[:new, :create]
    before_action :require_login
    skip_before_action :require_login, only: [:new, :create]
    

    def show
        if @user
            if @user.id != session[:user_id]
                return head(:forbidden) 
            end 
        else  
            return head(:forbidden) 
        end
    end

    def new
        if logged_in?
            redirect_to user_path(session[:user_id])
        else
            @user = User.new
        end
    end

    def create
        @user = User.new(user_params)
            if  @user.valid?
                @user.save
                session[:user_id] = @user.id
                redirect_to user_path(@user)
            else 
                render :new
            end
    end

    def edit
            if @user
                if @user.id != session[:user_id]
                    return head(:forbidden) 
                end 
            else  
                return head(:forbidden) 
            end
    end

    def update
        if @user.valid?
            @user.update(user_params)
            redirect_to user_path(@user)
        else
            render :edit 
        end
    end

    def destroy
        session.delete(:user_id)
        @user.destroy
        redirect_to root_path
    end


    private

    def user_params
        params.require(:user).permit(:username, :password, :email, :age, :about)
    end

    def set_user_variable
        @user = User.find_by_id(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def home
        if logged_in?
            redirect_to user_path(session[:user_id])
        end
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper

    def current_user
        @current_user ||= User.find_by_id(session[:user_id])
    end

    def logged_in?
        !!current_user
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/games_helper.rb
module GamesHelper

end

app/helpers/reviews_helper.rb
module ReviewsHelper

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/categories/index.html.erb
<div class='container'>
  <%= form_tag search_path, :method => 'get' do %>
      <%= text_field_tag :search, params[:search], :id =>"searchInput",:placeholder =>"Search.." %>
      <div id='submitsearch' style="">
        <%= submit_tag "Search for Game", :name => nil, :id => 'submitsearch',:style =>""%>
      </div>
  <% end %>
</div>

<div class='button_location'>
  <%@categories.each do |category|%>
      <button><%= link_to category.name, category_path(category)%></button>
  <%end%>
</div>

app/views/categories/show.html.erb
<h1><%=@category.name%>'s Games </h1>

<%@category.games.each do |game|%>
    <div class="row">
        <div class="column">
            <img src="<%= game.image%>" >
            <h3><%= link_to game.title, game_path(game) %></h3>
            <p> <%=game.description%> </p>
            <h4> <%= game.category.name%> </h4>
        </div>
    </div>
<%end%>

app/views/games/_form.html.erb
<div class='center_errors'>
    <%if @game.errors.any? %>
      <div id="error_explanation">
        <div class="bar">
          <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>
        </div>
        <ul>
          <% @game.errors.each do |error| %>
          <div class="bar">
            <div class="bar error"><li><%= error.full_message %></li></div>
            </div>
          <% end %>
        </ul>
      </div>
    <% end %>
</div>


<%= form_for @game do|f| %>
    <%=f.label :title%><br>
    <%=f.text_field :title%><br><br>

    <%=f.label "Please enter URL of image "%><br>
    <%=f.text_field :image%><br><br>

    <%=f.label :description%><br>
    <%=f.text_area :description%><br><br>

    Select a category<br>
    <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "select"}%><br>
    
    <%= f.fields_for :category do |category_attributes|%>
      Create a Category 
          <%= category_attributes.text_field :name %>
    <% end %>

    <%=f.submit%>
  <% end %>

app/views/games/_games.html.erb
       
 <div class="column">
    <img src="<%= game.image%>" >
    <h3><%= link_to game.title, game_path(game) %></h3>
    <p> <%=game.description%> </p>
    <button><h4> <%= link_to game.category.name, category_path(game.category)%> </h4></button>
</div>
       

app/views/games/edit.html.erb
<h1>Edit Games</h1><br>
 
<div class='form'>
    <%= render partial: "form" %>

    <button><%= link_to "Cancle", game_path(@game), method: 'get'%></button>
</div>

app/views/games/index.html.erb
<div class='button_location'>
        <button><h3><%= link_to "New Game", new_game_path(@game) %></h3></button>
</div>

<div class="grid-container">
    <%@games.each do |game|%>
        <%= render partial: "games", locals: {game: game} %>  
    <%end%>
</div>

app/views/games/new.html.erb
<h1>Create a Game</h1><br>

<div class='form'>
    <%= render partial: "form" %>
</div>

app/views/games/search.html.erb
<br><br><br><br><br><br>

<h1>Search Results </h1>

<% @games_search.each do |result|%>
    <%= render partial: "games", locals: {game: result} %>
<%end%>

app/views/games/show.html.erb
<%= render partial: "games", locals: {game: @game} %>

<div class='button_location'>
    <div class='game_show_page_buttons'>
        <button class ='button1'><%= link_to "Edit Game", edit_game_path(@game), method: 'get'%></button>
        <button class ='button2'><%= link_to "Reviews", game_reviews_path(@game), method: 'get'%></button>
    </div>
</div>

app/views/layouts/_navs.html.erb
    
    
<% if current_user%>
    <h1 class ="game_logo"><img class= 'header_img' src="https://cdn.iconscout.com/icon/free/png-512/game-wireless-remote-controller-gamepad-device-joypad-25-17843.png">Game App</h1>
    <ul class="menu">
          <li><%= link_to "Home", categories_path, method: 'get'%></li>
          <li><%= link_to "Profile", user_path(current_user), method: 'get'%></li>
          <li><%= link_to "Games", games_path, method: 'get'%></li>
          <li><%= link_to "Logout", signout_path, method: 'post'%></li>
          <li class="slider"></li>
      </ul>
<%else%>
    <h1 class ="game_logo">Game App</h1>
    <ul class="menu">
          <li class='image_link'><%= link_to root_path do %>
              <%= image_tag "https://cdn.iconscout.com/icon/free/png-512/game-wireless-remote-controller-gamepad-device-joypad-25-17843.png" %>
          <% end %>
          </li>
          <li><%= link_to "Sign In", signin_path%></li>
          <li><%= link_to "Sign Up", signup_path%></li>
          <li><%= link_to "Sign In with Google", '/auth/google_oauth2', method: 'post' %></li>
          <li class="slider"></li>
    </ul>
<%end%>
        
      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
     
    <%= render "layouts/navs" %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/error_page.html.erb
<h2><%=@message%></h2>
<h1>PAGE NOT FOUND</h1>

app/views/reviews/_buttons.html.erb
 <%if current_user == review.user%>
    <button><%= link_to "Edit Review", edit_game_review_path(@game,review)%></button>
    <button><%= link_to "Delete Review", game_review_path(@game, review), method: 'delete' %></button>
<%end%>

app/views/reviews/_form.html.erb
<div class='center_errors'>
    <%if @review.errors.any? %>
      <div id="error_explanation">
        <div class="bar">
          <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
        </div>
        <ul>
          <% @review.errors.each do |error| %>
          <div class="bar">
            <div class="bar error"><li><%= error.full_message %></li></div>
          </div>
          <% end %>
        </ul>
      </div>
    <% end %>
</div>


<div class='form'>
  <%= form_for ([@game, @review]) do|f| %>
    <%= f.hidden_field :game_id, :value => @game.id%>

    <%=f.label :content%><br>
    <%=f.text_area :content%><br><br>


    <%=f.submit%>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<%= render partial: 'form'%>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<div class='button_location'>
    <button><h3><%= link_to "New Review", new_game_review_path(@game) %></h3></button>
</div>

<div class="grid-container ">
        
    <div class="column">
        <img src="<%= @game.image%>" >
        <h3><%= link_to @game.title, game_path(@game) %></h3>
        <p> <%=@game.description%> </p>
        <button><h4> <%= link_to @game.category.name, category_path(@game.category)%> </h4></button>
    </div>
    
    
    <div class="column">
        <h3>Reviews:</h3>
        <%@reviews.each do |review|%>
            <div class ="review_content">
                <h4><%=review.user.username%></h4>
                <p><%=review.content%></h4>
            </div>
            <%= render partial:'buttons', locals: {review: review}%>
        <%end%>
    </div>
</div>

app/views/reviews/new.html.erb
<%= render partial: 'form'%>

app/views/users/_form.html.erb
<div class='center_errors'>
    <%if @user.errors.any? %>
      <div id="error_explanation">
        <div class="bar">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
        </div>
        <ul>
          <% @user.errors.each do |error| %>
          <div class="bar">
            <div class="bar error"><li><%= error.full_message %></li></div>
          </div>
          <% end %>
        </ul>
      </div>
    <% end %>
</div>

<div class='form'>

  <%= form_for @user, url: signup_path do|f| %>
  <%=f.label :username%>
  <%=f.text_field :username%><br>
  <%=f.label :age%><br>
  <%=f.text_field :age%><br>
  <%=f.label :about%><br>
  <%=f.text_area :about%><br>
  <%=f.label :email%><br>
  <%=f.text_field :email%><br>
  <%=f.label :password%>
  <%=f.password_field :password%><br><br>
  
  <%=f.submit%>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit Profile</h1><br>
 
<div class='form'>
    <%= form_for @user do|f| %>
        <%=f.label :username%>
        <%=f.text_field :username%><br><br>
        <%=f.label :age%><br>
        <%=f.text_field :age%><br><br>
        <%=f.label :about%><br>
        <%=f.text_area :about%>
        
        <%=f.submit%>
        <button><%= link_to "Cancel", user_path(@user), method: 'get', :class => "button" %></button>
    <% end %>

    <h4> Would you like to delete you account?</h4>
    <button><%= link_to "Delete Account", user_path(@user), method: 'delete',:class => "button" %></button>

</div>

app/views/users/new.html.erb
<h1>Signup</h1>
 
<%= render partial: "form" %>

app/views/users/show.html.erb
<div class='profile_page_container'>

    <h2>Welcome: <%=@user.username.upcase%><br><br><h2>
    <h3>Age: <%=@user.age%><br><br><h3>
    <h3>About Me: <br></h3>
    <p><%=@user.about%><br><br></p>

   

    <button><%= link_to "Edit Profile", edit_user_path(@user), method: 'get', :class => "button" %></button>

</div>

app/views/welcome/home.html.erb
<div class='center_errors'>
    <% if flash[:alert] %>
        <ul>
            <% flash.each do |type, msg| %>
                <div class="bar">
                    <div class="bar error"><li><%= msg %><li></div>
                </div>
            <% end %>
        </ul>
    <% end %>
</div>


	<h1 class='welcome_text'>Welcome</h1>